<h1>About</h1>

<p>
hs-wiki is a small experimental wiki-software written in 
<a href="http://haskell.org">Haskell</a> using the Web-Framework 
<a href="http://happs.org/">HAppS</a>. This wiki was primary written to 
learn a bit Web-Development on Haskell and is not dedicated for productive 
operation. It uses MACID as backend-storage for articles and users. Moreover
the wiki will no longer be further developed.
</p>
<p>
Feel free to fork the code on github, improve the project and give me some
tipps developing with Haskell and HAppS :).
</p>
<p>
hs-wiki &copy; Michael Opitz
</p>
